openapi: 3.0.0
info:
  title: Parking Management System API
  version: 1.0.0
paths:
  /auth/signup:
    post:
      summary: User Signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSignup'
      responses:
        '200':
          description: Success
  /auth/login:
    post:
      summary: User Login
      responses:
        '200':
          description: Success
components:
  schemas:
    UserSignup:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
